# GitHub Actions Release Workflow Contract
# This file documents the expected .github/workflows/release.yml structure
# Actual implementation will be at: .github/workflows/release.yml

name: Release

on:
  push:
    tags:
      - 'v*'

permissions:
  contents: write      # Create releases
  packages: write      # Push Docker images to ghcr.io

concurrency:
  group: release-${{ github.ref }}
  cancel-in-progress: true

jobs:
  test:
    name: Pre-release Tests
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Run tests
        run: go test -short -race ./...

      - name: Run linter
        uses: golangci/golangci-lint-action@v4
        with:
          version: latest

  release:
    name: Release
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.21'
          cache: true

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Create completions directory
        run: mkdir -p completions

      - name: Run GoReleaser
        uses: goreleaser/goreleaser-action@v5
        with:
          distribution: goreleaser
          version: latest
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          HOMEBREW_TAP_GITHUB_TOKEN: ${{ secrets.HOMEBREW_TAP_GITHUB_TOKEN }}

  verify:
    name: Verify Release
    needs: release
    runs-on: ubuntu-latest
    steps:
      - name: Verify Docker image
        run: |
          docker pull ghcr.io/systmms/dsops:${{ github.ref_name }}
          docker run --rm ghcr.io/systmms/dsops:${{ github.ref_name }} --version

      - name: Verify GitHub Release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: |
          gh release view ${{ github.ref_name }} --repo ${{ github.repository }}

# Notes:
# - HOMEBREW_TAP_GITHUB_TOKEN: Personal access token with repo scope for systmms/homebrew-dsops
# - If Homebrew update fails, formula can be manually updated
# - Pre-releases (e.g., v1.0.0-beta.1) skip Homebrew and :latest Docker tag
