# GoReleaser configuration for dsops
# https://goreleaser.com

version: 2

project_name: dsops

before:
  hooks:
    - go mod tidy
    - go generate ./...
    # Generate shell completions before cross-compilation
    # (must use go run since we can't execute cross-compiled binaries)
    - mkdir -p completions
    - go run ./cmd/dsops completion bash > completions/dsops.bash
    - go run ./cmd/dsops completion zsh > completions/dsops.zsh
    - go run ./cmd/dsops completion fish > completions/dsops.fish

builds:
  - id: dsops
    binary: dsops
    main: ./cmd/dsops
    env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.ShortCommit}}
      - -X main.date={{.Date}}

archives:
  - id: default
    formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - LICENSE
      - README.md
      - completions/*

checksum:
  name_template: "{{ .ProjectName }}_{{ .Version }}_checksums.txt"
  algorithm: sha256

changelog:
  use: github-native
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^ci:"
      - "^chore:"
      - "Merge pull request"
      - "Merge branch"
  groups:
    - title: Features
      regexp: "^feat"
      order: 0
    - title: Bug Fixes
      regexp: "^fix"
      order: 1
    - title: Performance
      regexp: "^perf"
      order: 2
    - title: Other
      order: 999

release:
  github:
    owner: systmms
    name: dsops
  draft: false
  prerelease: auto
  name_template: "v{{ .Version }}"

brews:
  - name: dsops
    repository:
      owner: systmms
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    directory: Formula
    homepage: "https://github.com/systmms/dsops"
    description: "Secret management for development and production environments"
    license: "MIT"
    skip_upload: auto  # Skip for pre-releases
    test: |
      system "#{bin}/dsops", "--version"
    install: |
      bin.install "dsops"
      bash_completion.install "completions/dsops.bash" => "dsops"
      zsh_completion.install "completions/dsops.zsh" => "_dsops"
      fish_completion.install "completions/dsops.fish"

dockers:
  - image_templates:
      - "ghcr.io/systmms/dsops:{{ .Version }}"
      - "ghcr.io/systmms/dsops:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--build-arg=VERSION={{ .Version }}"
      - "--label=org.opencontainers.image.version={{ .Version }}"
      - "--label=org.opencontainers.image.source={{ .GitURL }}"
      - "--label=org.opencontainers.image.revision={{ .FullCommit }}"
      - "--label=org.opencontainers.image.created={{ .Date }}"
    skip_push: auto  # Skip :latest for pre-releases
