# gosec security scanner configuration
# See: https://github.com/securego/gosec#configuration
#
# This config excludes security rules that are intentional design choices
# for dsops as a CLI tool that manages secrets and executes commands.

global:
  # Show what would be reported without failing (for debugging)
  # audit: enabled

# Rules to exclude globally
# These patterns are intentional for a CLI tool like dsops
excludes:
  # G204 - Subprocess launched with variable
  # dsops intentionally executes user-specified commands via:
  # - `dsops exec` command (ephemeral execution with secrets)
  # - `dsops guard` command (pre-commit hooks)
  # - Health check scripts during rotation
  - G204

  # G304 - File inclusion via variable
  # dsops reads files by design:
  # - Configuration files (dsops.yaml)
  # - Template files for rendering
  # - dsops-data service definitions
  # - Rotation state files
  - G304

  # G301 - Directory permissions >0750
  # 0755 is acceptable for:
  # - State directories that need to be readable
  # - Git hooks directories
  # - Cache directories
  - G301

  # G306 - File permissions >0600
  # 0644 is acceptable for:
  # - Non-secret state files (rotation status, progress)
  # - Test configuration files
  # Actual secret files use 0600 permissions
  - G306

  # G107 - HTTP request with variable URL
  # dsops sends notifications to user-configured webhook URLs:
  # - Slack webhooks
  # - PagerDuty endpoints
  # - Custom notification endpoints
  - G107
